blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Ifihan/certificate-generator/blob/main/README.md
    about: Check out the README for setup instructions and usage guide
  - name: Contributing Guide
    url: https://github.com/Ifihan/certificate-generator/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to the project
